version: "3.8"

services:

  frontend:
    image: frontend-image
    container_name: frontend
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000

  redis:
    image: redis
    container_name: redis

  backend:
    container_name: backend
    image: backend-image
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment:
      - API_URL=http://localhost:5000
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=user
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=db

    depends_on:
      - redis
      - db

  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=datamodel