version: "3.8"

services:

  redis:
    image: redis
    build: ./redis
    restart: unless-stopped
    ports:
      - 6379

  backend:
    image: backend-image
    build: ./backend
    ports:
      - 4001:8000
    environment:
      - FRONT_URL=http://localhost:4000
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=user
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=db

    depends_on:
      - redis
      - db

  frontend:
    image: frontend-image
    build: ./frontend
    ports:
      - 4000:5000
    environment:
      - API_URL=http://localhost:4001
    depends_on:
      - backend

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres