version: "3.8"

services:

  backend:
    container_name: backend
    image: backend-image
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment:
      - FRONT_URL=http://localhost
      - REDIS=redis
      - DB_USERNAME=user
      - DB_PASSWORD=example
      - DB_NAME=datamodel
      - DB_HOST=postgres

  frontend:
    image: frontend-image
    ports:
      - 5000:5000
    container_name: frontend
    environment:
      - API_URL=http://localhost/api

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=datamodel

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf